### ISSUE TITLE
Use `noarch`

### ISSUE THREAD

**Issue by adibbley** [conda-forge/cuda-libraries-feedstock#3]
xref https://github.com/conda-forge/cuda-feedstock/issues/4

> As this package doesn't have any architecture dependency on its own, it would make sense to make this noarch. This would allow this package to be built once and reused on other architectures/OSes, which would simply the release process and cutdown on resource usage. For dependencies that are architecture/OS dependent, the right package would be pulled in. Raising to track evaluating this option

**Comment by jakirkham** [comment]
Given how we need to specify the `cuda-opencl` dependency, this is not solvable atm

https://github.com/conda-forge/cuda-libraries-feedstock/blob/865dab4327e962ed2f16b7825caa391004853c78/recipe/meta.yaml#L19

Going to close this as won't fix. If things change, we can always revisit
